blank_issues_enabled: true
contact_links:
  - name: Discussions
    url: https://github.com/praxis-proxy/praxis/discussions
    about: Ask questions or start a discussion
  - name: Enhancements
    url: https://github.com/praxis-proxy/enhancements
    about: Centralized enhancement proposals repository
