// SPDX-License-Identifier: MIT
// Copyright (c) 2024 Shane Utt

//! Conversation state abstraction for stateful AI gateway features.
//!
//! This module defines [`ConversationBackend`], a pluggable trait for storing
//! and retrieving multi-turn conversation history

use std::{
    sync::Arc,
    time::{Duration, SystemTime, UNIX_EPOCH},
};

use async_trait::async_trait;

/// Pluggable backend for storing and retrieving conversation history.
///
/// # Id uniqueness
///
/// Conversations ids are UUID v4, generated by the backend on `create` and
/// globally unique
///
/// # TTL semantics
///
/// `create` sets the initial TTL. `append` accepts an optional `ttl` to refresh
/// it on each new message.
/// Backends that do not support TTL refresh may ignore the `ttl` on `append`
///
/// # Scope isolation
///
/// All operations take a `ConversationScope`. It is up to backend to verify
/// that stored scope matches the requested scope on each operation, returning
/// [`ConversationError::ScopeMismatch`] on failure
#[async_trait]
pub trait ConversationBackend: Send + Sync {
    /// Start a new conversation with the given initial messages.
    ///
    /// The backend generates a UUID v4 conversation Id and returns it.
    async fn create(
        &self,
        scope: ConversationScope,
        messages: Vec<ConversationMessage>,
        ttl: Duration,
    ) -> Result<Arc<str>, ConversationError>;

    /// Retrieve a conversation by Id
    ///
    /// Returns `None`  if the conversation does not exist or has expired. Missing
    /// conversation is not an error, callers decide whether to start fresh
    /// or return an error to the client.
    /// Returns `ScopeMismatch` if the conversation exists but was created
    /// under a different scope
    async fn get(&self, scope: &ConversationScope, id: &str) -> Result<Option<ConversationEntry>, ConversationError>;

    /// Append new messages to an existing conversation and return the updated
    /// entry.
    ///
    /// ## TTL
    ///
    /// `ttl = None`: the existing expiry deadline is left unchanged.
    ///
    /// `ttl = Some(d)`: deadline is reset to `now + d`, replacing the previous
    /// value
    ///
    /// ## Errors
    ///
    /// - Returns [`ConversationError::NotFound`] if the conversation does not
    /// exist, callers must handle this explicitly rather than allowing a
    /// silent new conversation to be created.
    /// - Returns [`ConversationError::ScopeMismatch`] if the entry exists under
    /// a different scope.
    /// - Returns [`ConversationError::Unavailable`] if the backend cannot be
    /// reached
    async fn append(
        &self,
        scope: &ConversationScope,
        id: &str,
        messages: Vec<ConversationMessage>,
        ttl: Option<Duration>,
    ) -> Result<ConversationEntry, ConversationError>;

    /// Delete a conversation.
    ///
    /// idempotent: deleting a non-existent or already expired conversation
    /// returns `Ok(())`.
    ///
    /// Returns `ScopeMisMatch` if the conversation exists but belongs to a
    /// different scope
    ///
    /// ## Errors
    ///
    /// - Returns [`ConversationError::ScopeMismatch`] if the entry exists under
    /// a different scope.
    /// - Returns [`ConversationError::Unavailable`] if the backend cannot be
    /// reached.
    async fn delete(&self, scope: &ConversationScope, id: &str) -> Result<(), ConversationError>;
}

/// Identifies the owner of a conversation and helps backends to enforces
/// isolation boundaries for all backend operations
///
/// There is an explicit hierarchy:
/// - a `Session` always belong to a `User`
/// - a `User` always belong to a `Tenant`
///
/// Note: `Global` is provided for development, single-tenant deployments, and
/// integration tests where isolation is not required.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum ConversationScope {
    /// Global scope for test or single Tenant
    Global,
    /// Tenant scope
    Tenant {
        /// `tenant_id`
        tenant_id: Arc<str>,
    },
    /// User scope. All users belong to a tenant
    User {
        /// `tenant_id`
        tenant_id: Arc<str>,
        /// `user_id`
        user_id: Arc<str>,
    },
    /// Session scope: all sessions belong to a user
    Session {
        /// `tenant_id`
        tenant_id: Arc<str>,
        /// `user_id`
        user_id: Arc<str>,
        /// `session_id`
        session_id: Arc<str>,
    },
}

/// Role of a message in a conversation
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum MessageRole {
    /// System prompt
    System,
    /// Human
    User,
    /// Model
    Assistant,
    /// Tool result being fed back into the model.
    Tool {
        /// `call_id` links this result with the original trigger
        call_id: Arc<str>,
    },
}

/// One Conversation message
#[derive(Clone, Debug)]
pub struct ConversationMessage {
    /// Message author role
    role: MessageRole,
    /// Raw message content
    content: serde_json::Value,
    /// Unit timespamp in ms when this message was recorded
    created_at_ms: u64,
}

impl ConversationMessage {
    /// constructor
    pub fn new(role: MessageRole, content: serde_json::Value) -> Self {
        Self {
            role,
            content,
            created_at_ms: now_ms(),
        }
    }

    /// getter
    pub fn role(&self) -> &MessageRole {
        &self.role
    }

    /// getter
    pub fn content(&self) -> &serde_json::Value {
        &self.content
    }

    /// getter
    pub fn created_at_ms(&self) -> u64 {
        self.created_at_ms
    }
}

/// A complete conversation
#[derive(Clone, Debug)]
pub struct ConversationEntry {
    /// Globally unique conversation id (UUID v4) returned
    /// by [`ConversationBackend::create`]
    id: Arc<str>,
    /// Scope under which this conversation was create
    scope: ConversationScope,
    /// Ordered list of messages in the conversation, olders firts
    messages: Vec<ConversationMessage>,
    /// Unix timestamp in ms when this conversation was created
    created_at_ms: u64,
    /// Unix timestamp in ms when this conversation will expire.
    expires_at_ms: u64,
}

impl ConversationEntry {
    /// Globally unique conversation id (UUID v4) returned
    /// by [`ConversationBackend::create`]
    pub fn id(&self) -> Arc<str> {
        Arc::clone(&self.id)
    }

    /// Scope under which this conversation was create
    pub fn scope(&self) -> &ConversationScope {
        &self.scope
    }

    /// Ordered list of messages in the conversation, olders firts
    pub fn messages(&self) -> &[ConversationMessage] {
        &self.messages
    }

    /// Unix timestamp in ms when this conversation was created
    pub fn created_at_ms(&self) -> u64 {
        self.created_at_ms
    }

    /// Unix timestamp in ms when this conversation will expire.
    pub fn expires_at_ms(&self) -> u64 {
        self.expires_at_ms
    }
}

/// Errors returned by [`ConversationBackend`] operations
#[derive(Debug, thiserror::Error)]
pub enum ConversationError {
    /// Backend unreachable or timeout
    #[error("conversation backend unavailable: {0}")]
    Unavailable(String),

    /// conversation not found or has expired
    #[error("conversation not found: {0}")]
    NotFound(Arc<str>),

    /// The requested scope does not match the scope stored with the entry
    #[error("scope mismatch for conversation: {0}")]
    ScopeMismatch(Arc<str>),

    /// A field value was invalid( empty id, oversized content, etc )
    #[error("invalid input: {0}")]
    InvalidInput(String),

    /// Backend returned an unexpected error
    #[error("backend error: {0}")]
    Backend(String),
}

/// Returns the current time as Unix timestamp in ms
///
/// Fallsback to `0` if system clock is set before Unix epoch
fn now_ms() -> u64 {
    u64::try_from(
        SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap_or_default()
            .as_millis(),
    )
    .unwrap_or(u64::MAX)
}
