name: Fuzz

# ------------------------------------------------------------------------------
# Workflow Settings
# ------------------------------------------------------------------------------

on:
  schedule:
    - cron: "52 2 * * *"
  workflow_dispatch:

permissions: {}

jobs:
  # -----------------------------------------------------------------
  # Fuzz
  # -----------------------------------------------------------------

  fuzz:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Install nightly Rust
        uses: dtolnay/rust-toolchain@5b842231ba77f5c045dba54ac5560fed2db780e2 # nightly-2026-03-28 (rustc 1.96.0)

      - name: Install cargo-fuzz
        run: cargo install cargo-fuzz --locked

      - name: Run fuzz targets
        run: make fuzz
