name: Publish

# ------------------------------------------------------------------------------
# Workflow Settings
# ------------------------------------------------------------------------------

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions: {}

jobs:
  # ----------------------------------------------------------------------------
  # Container Build & Publish
  # ----------------------------------------------------------------------------

  container:
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    if: >-
      github.event_name == 'push' ||
      github.event.workflow_run.conclusion == 'success'
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Build and publish container
        uses: praxis-proxy/conventions/.github/actions/ghcr-publish@bcfaea95ff4e6746587d54f6b6d6a62cfc5aa0e4 # v0.1.0
        with:
          image-name: ${{ github.repository }}
