name: SemVer

# ------------------------------------------------------------------------------
# Workflow Settings
# ------------------------------------------------------------------------------
#
# Shared from praxis-proxy/conventions (semver.yaml).

on:
  # NOTE: manual only until v1.x.x
  workflow_dispatch:

permissions: {}

jobs:
  semver:
    permissions:
      contents: read
    uses: praxis-proxy/conventions/.github/workflows/semver.yaml@c5837c3fdd35066b05d337594fabe9d641d08df2 # v0.3.0
